HorizonMedia/HealthMarketWebsite

- src/components/Inputs/Autocomplete/index.tsx
- src/components/Lists/ListItem/index.tsx
- src/components/Medials/index.tsx
- src/components/RelatedContent/index.tsx
Fixes missing deps on useEffect that are deps-less and run on every render
> Fix: dodgy useeffects

- src/components/pages/styles/DentalInsStyles.ts
- src/components/pages/styles/HealthInsStyles.ts
- src/components/pages/styles/HowWeHelpStyles.ts
- src/components/pages/styles/MedicareStyles.ts
- src/components/pages/styles/SupplementalInsStyles.ts
Refactored selectors across several pages to avoid a style targeting error.
> Dev merge to fix site styles

- .env.development
- gatsby-config.js
- src/components/Buttons/Button/styles.ts
- src/components/Buttons/ToggleButton/styles.ts
- src/components/Buttons/index.tsx
- src/components/Callouts/Callout/styles.ts
- src/components/Cards/Card/styles.ts
- src/components/Footer/styles.ts
- src/components/Header/HeaderRight/index.tsx
- src/components/Header/HeaderRight/styles.ts
- src/components/Header/styles.ts
- src/components/Hero/PageHeroForm/index.tsx
- src/components/Hero/PageHeroForm/styles.ts
- src/components/Hero/styles.ts
- src/components/Inputs/Geocode/AutocompleteField/index.tsx
- src/components/Inputs/Geocode/AutocompleteField/styles.ts
- src/components/Layout/styles.ts
- src/components/Navigation/AfterNav/index.tsx
- src/components/RelatedContent/styles.ts
- src/components/Tiles/Tile/styles.ts
- src/components/pages/styles/ContactStyles.ts
- src/pages/contact/index.tsx
- src/pages/dental-insurance/index.tsx
- src/pages/health-insurance/index.tsx
- src/pages/how-we-help/index.tsx
- src/pages/index.tsx
- src/pages/medicare/index.tsx
- src/pages/supplemental-insurance/index.tsx
- src/pages/{wpProduct.slug}.tsx
Merging in dev updates for cards and phone numbers
> Dev updates for cards and phone numbers

- src/components/Header/HeaderRight/index.tsx
- src/components/Hero/styles.ts
- src/components/Navigation/AfterNav/index.tsx
Hotfix for a couple small bugs.
> Hotfix for a couple small bugs.

- src/components/Cards/Card/index.tsx
- src/components/Cards/Card/styles.ts
- src/components/Footer/FooterMenu/index.tsx
- src/components/Footer/PlansByStateMenu.tsx
- src/components/Footer/component.tsx
- src/components/Header/HeaderRight/index.tsx
- src/components/Header/index.tsx
- src/components/Icons/Icon/index.tsx
- src/components/Layout/component.tsx
- src/components/Navigation/AfterNav/index.tsx
- src/components/Navigation/index.tsx
- src/components/Tiles/Tile/index.tsx
- src/pages/404.tsx
- src/pages/dental-insurance/index.tsx
- src/pages/health-insurance/index.tsx
- src/pages/index.tsx
- src/pages/medicare/index.tsx
- src/pages/supplemental-insurance/index.tsx
- src/pages/{wpLandingPage.slug}.tsx
- src/pages/{wpProduct.slug}.tsx
- src/static/scripts/global.tsx
Hotfix for links not persisting tracking data while on the core site.
> Hotfix for links not persisting tracking data while on the core site.

- src/components/Accordions/styles.ts
- src/components/Cards/Card/styles.ts
- src/components/Navigation/styles.ts
Arrows now face down when closed and up when open
> Merging arrow orientation updates

- src/components/Hero/index.tsx
- src/components/Hero/styles.ts
- src/components/pages/styles/ContactStyles.ts
- src/components/pages/styles/LandingPageStyles.ts
- src/pages/contact/index.tsx
- src/pages/{wpLandingPage.slug}.tsx
- src/pages/{wpProduct.slug}.tsx
- src/static/scripts/global.tsx
> Merging in Medicare Quoter Landing Page for staging

- src/components/Inputs/Checkbox/index.tsx
- src/components/pages/styles/ContactStyles.ts
- src/components/pages/styles/LandingPageStyles.ts
- src/pages/contact/index.tsx
- src/pages/{wpLandingPage.slug}.tsx
- src/static/scripts/global.tsx
Updating asterisks and disclaimers for the Medicare Quoter LP
> Updating asterisks and disclaimers for the Medicare Quoter LP

- src/components/pages/styles/LandingPageStyles.ts
Centering copy bits at device widths.
> Centering copy bits at device widths.

- .env.development
- src/pages/{wpLandingPage.slug}.tsx
Merging in latest quoterlp updates
> Merging in latest quoterlp updates

- src/components/Hero/index.tsx
- src/components/Hero/styles.ts
- src/pages/{wpLandingPage.slug}.tsx
Restoring landing page updates to support the quoter landing pages again
> Restoring landing page updates to support the quoter landing pages again

- src/pages/{wpLandingPage.slug}.tsx
Merging capitalization changes from Quoterlp
> Merging capitalization changes from Quoterlp

- src/components/Hero/styles.ts
Updated the hero image top positioning to better fit the images selected by HM.
> Updated the hero image top positioning to better fit the images selected by HM.

- src/api/contact-form.ts
- src/components/Forms/ContactForm.tsx
- src/components/Modals/index.tsx
- src/components/Modals/styles.ts
- src/pages/contact/index.tsx
- src/static/scripts/global.tsx
Contact form confirmation message and functionality fixes
> Contact form confirmation message and functionality fixes

- src/components/Hero/PageHeroForm/index.tsx
- src/components/pages/styles/MedicarePrescriptionDrugStyles.ts
- src/components/pages/styles/SupplementalInsStyles.ts
- src/pages/medicare/medicare-prescription-drug/index.tsx
Organize styles according to the pages they belong.
> Medicare pages changes

- src/components/PageHead.tsx
Fixed analytics configuration causing visibility delays.
> Changed opacity in the analytics configuration script

- src/components/Header/HeaderRight/index.tsx
- src/components/Navigation/AfterNav/index.tsx
- src/components/Navigation/styles.ts
- src/components/Sections/FlexedSection/styles.ts
- src/hooks/insurance/useFinalExpensePageQuery.tsx
- src/hooks/insurance/useMedicareAdvantagePageQuery.tsx
- src/hooks/insurance/useMedicarePrescriptionDrugPageQuery.tsx
- src/hooks/insurance/useShortTermPageQuery.tsx
Also committed page id fixes for pushing to dev env.
> New header updates

- src/components/Header/index.tsx
- src/components/Hero/PageHeroForm/index.tsx
- src/components/Hero/PageHeroForm/styles.ts
- src/components/pages/styles/FinalExpenseStyles.ts
- src/pages/life-insurance/final-expense-insurance/index.tsx
This PR contains the entire Final Expense Page redesign in Desktop and Mobile.
Here is the [figma](https://www.figma.com/file/nZKcLyJKOt93ghL9DVbPnU/CLIENT---Landing-Pages?type=design&node-id=3563-1794&mode=design&t=NVr0xcg3OfoSSge6-0) file for reference: 
Jira Ticket: [https://horizonmedia.atlassian.net/browse/NMB-138](https://horizonmedia.atlassian.net/browse/NMB-103)
> NMB-103: Final Expense Page Update

- src/components/pages/styles/FinalExpenseStyles.ts
- src/pages/life-insurance/final-expense-insurance/index.tsx
Additional changes for Final Expense Page.
Refer to: [https://github.com/HorizonMedia/HealthMarketWebsite/pull/130](https://github.com/HorizonMedia/HealthMarketWebsite/pull/130)
> NMB-103: Final Expense Page Update Part 2

- src/components/Footer/FooterMenu/index.tsx
The changes made in this pull request stops the Do not Share or Sell My Information link from opening in a new tab.
Jira Ticket: [https://horizonmedia.atlassian.net/browse/NMB-138](https://horizonmedia.atlassian.net/browse/NMB-138)
> Do not Share or Sell My Information disable new tab 

- src/components/pages/styles/FinalExpenseStyles.ts
Additional changes for Final Expense Page.
Refer to: https://github.com/HorizonMedia/HealthMarketWebsite/pull/130
> Fixed active nav colors

- src/components/Inputs/Geocode/AutocompleteField/index.tsx
Jira Ticket: [https://horizonmedia.atlassian.net/browse/NMB-81](https://horizonmedia.atlassian.net/browse/NMB-81)
> Fixed zipcode bug

- src/components/Header/HeaderRight/index.tsx
- src/components/Header/LPHeader/index.tsx
- src/components/Navigation/AfterNav/index.tsx
- src/pages/medicare/medicare-advantage/index.tsx
- src/pages/medicare/medicare-prescription-drug/index.tsx
Changed all "TTY 771" instances to "TTY 711".
Jira Ticket: [https://horizonmedia.atlassian.net/browse/NMB-188](https://horizonmedia.atlassian.net/browse/NMB-188)
> Changed all "TTY 771" instances to "TTY 711"

- src/components/pages/styles/FinalExpenseStyles.ts
Updates to copy sizing to match https://www.healthmarkets.com/health-insurance/short-term/?utm_medium=direct
Resolves ticket [NMB-103](https://horizonmedia.atlassian.net/browse/NMB-103?atlOrigin=eyJpIjoiZWQ2OTIzYjQ2ZTcxNGM0ZWI1ZmE1NGJkNTVkYzRjODYiLCJwIjoiaiJ9)
Before
After
> NMB-103: Updating font for Final Expense

- package-lock.json
- src/components/Cards/Card/index.tsx
- src/components/Header/HeaderRight/styles.ts
- src/components/Lists/ListItem/styles.ts
- src/components/pages/styles/IntelligentPageStyles.ts
- src/hooks/insurance/useIntelligentPageQuery.tsx
- src/pages/dental-insurance/index.tsx
- src/pages/health-insurance/intelligent-insurance/index.tsx
For this pull request, I made the the Intelligent Insurance page following the figma design and insuring that it meet the criteria from desktop to mobile version
JIRA Ticket: https://horizonmedia.atlassian.net/jira/software/projects/NMB/boards/89?selectedIssue=NMB-137
Figma design link https://www.figma.com/file/8AYPPwrY3KfhK3SVMouDhb/CLIENT---Intelligent-Lead-Gen-Email-%2B-LP?type=design&node-id=889-407&mode=design&t=mHdHZkl0CQdcVISm-0
> Creation of Intelligent Insurance Page

- src/components/Footer/FooterMenu/index.tsx
- src/components/Header/HeaderRight/index.tsx
- src/components/Header/LPHeader/index.tsx
- src/components/Navigation/AfterNav/index.tsx
- src/pages/medicare/medicare-advantage/index.tsx
Needs to be merged into Production
> Merge into prod

- src/components/Header/index.tsx
- src/components/Hero/PageHeroForm/index.tsx
- src/components/Hero/PageHeroForm/styles.ts
- src/components/pages/styles/FinalExpenseStyles.ts
- src/hooks/insurance/useFinalExpensePageQuery.tsx
- src/pages/life-insurance/final-expense-insurance/index.tsx
Release Notes:
- Final Expense page deployment. 
Jira Ticket: [https://horizonmedia.atlassian.net/browse/NMB-103](https://horizonmedia.atlassian.net/browse/NMB-103)
> Release: 9/14/2024

- src/components/pages/styles/FinalExpenseStyles.ts
- src/hooks/insurance/useFinalExpensePageQuery.tsx
Requested to stack buttons in mobile view.
> Stack page hero form in mobile view.

- src/components/pages/styles/IntelligentPageStyles.ts
- src/pages/intelligent-insurance-plans/index.tsx
QA Fixes on ticket [NMB-137](https://horizonmedia.atlassian.net/browse/NMB-137?atlOrigin=eyJpIjoiOTVkZTEzNWYzNDRhNGQ1Nzk1OGEzYzQ4MDY1YTBmMmQiLCJwIjoiaiJ9)
> update card font colors

- src/components/Hero/PageHeroForm/styles.ts
- src/hooks/insurance/useFinalExpensePageQuery.tsx
The production `databaseId` was replaced with the localhost id.
Also found a bug with the CTA button that has been corrected. 
Jira ticket: [https://horizonmedia.atlassian.net/browse/NMB-103](https://horizonmedia.atlassian.net/browse/NMB-103)
> Hotfix: Final Expense Page CTA fix

- src/components/pages/styles/homePageStyles.ts
- src/hooks/useHomePageQuery.tsx
- src/pages/index.tsx
Updates to hero page styles and imagery
Resolves [NMB-91](https://horizonmedia.atlassian.net/browse/NMB-91?atlOrigin=eyJpIjoiNjdlOWU2YTM0NmY1NGJiYzhiZDg5ZjAxMjE0ZjAzYTQiLCJwIjoiaiJ9)
Relevant url: https://www.healthmarkets.com/
[Figma](https://www.figma.com/file/9xftUKeRnWmIPr65vwYYGx/CLIENT-Countdown-Clock?type=design&node-id=505-2130&mode=design&t=7dC4b2xpyFNAPDgz-0)
> update home page hero

- src/components/pages/styles/IntelligentPageStyles.ts
- src/hooks/insurance/useIntelligentPageQuery.tsx
- src/pages/intelligent-insurance-plans/index.tsx
Brightedge can't be used for dynamic material so a conditional needed to to be created. 
Jira Ticket: https://horizonmedia.atlassian.net/browse/NMB-137
> Brightedge conditional for ILG. 

- src/components/pages/styles/IntelligentPageStyles.ts
- src/pages/intelligent-insurance-plans/index.tsx
This PR fixes the related content header color. 
Jira ticket: https://horizonmedia.atlassian.net/browse/NMB-137
> Intelligent insurance page header color update

- src/components/Hero/PageHeroForm/index.tsx
- src/components/pages/styles/MedicareAdvantageStyles.tsx
- src/components/pages/styles/MedicareStyles.ts
- src/components/pages/styles/homePageStyles.ts
- src/pages/index.tsx
- src/pages/medicare/index.tsx
- src/pages/medicare/medicare-advantage/index.tsx
- src/pages/medicare/medicare-prescription-drug/index.tsx
9/29 fixes to home page and medicare pages
> Aep dev hotfixes

- src/components/pages/styles/MedicareAdvantageStyles.tsx
Resolves formatting issue from 9/30 email. Needs to be merged into dev and into release branch.
**Old:**
**New:**
> update pdp section header

- src/components/pages/styles/IndividualPageStyle.ts
This PR fixes the header section for the Individual Insurance Page. 
| Before        | After          | 
| ------------- |:-------------:| 
|![Screenshot 2023-10-03 at 1 17 17 PM](https://github.com/HorizonMedia/HealthMarketWebsite/assets/141367316/021da396-2813-4907-9577-ce674f27518c)|![Screenshot 2023-10-03 at 1 17 08 PM](https://github.com/HorizonMedia/HealthMarketWebsite/assets/141367316/3c9eff4b-3165-4b65-806c-6de096734fec)|
Jira Ticket for Individual Page: [https://horizonmedia.atlassian.net/browse/NMB-83](https://horizonmedia.atlassian.net/browse/NMB-83)
> NMB-83: Hotfix for individual header section

- src/components/Hero/styles.ts
- src/components/pages/styles/IntelligentPageStyles.ts
This PR fixes the header section for the ILG. 
| Before        | After          | 
| ------------- |:-------------:| 
|![Screenshot 2023-10-03 at 2 40 07 PM](https://github.com/HorizonMedia/HealthMarketWebsite/assets/141367316/8fdb98ee-3d26-4f18-8662-ab7356bfca2c)|![Screenshot 2023-10-03 at 2 42 21 PM](https://github.com/HorizonMedia/HealthMarketWebsite/assets/141367316/987c400b-bc3b-4895-a831-8f1c22869561)|
Jira Ticket for ILG: [https://horizonmedia.atlassian.net/browse/NMB-137](https://horizonmedia.atlassian.net/browse/NMB-137)
> NMB-137: Hotfix for individual header section

- src/components/pages/styles/IntelligentPageStyles.ts
- src/pages/intelligent-insurance-plans/index.tsx
Client requested new designs for ILG Page.
> Hotfix: New designs for ILG Page

- src/components/pages/styles/IndividualPageStyle.ts
- src/pages/health-insurance/individual-page/index.tsx
Align plan option line to dots.
> hotfix: update plan option line

- src/components/pages/styles/IndividualPageStyle.ts
- src/hooks/insurance/useIndividualPageQuery.tsx
- src/pages/health-insurance/individual/index.tsx
This PR creates the Individual Page.
Jira Ticket: [https://horizonmedia.atlassian.net/browse/NMB-83](https://horizonmedia.atlassian.net/browse/NMB-83)
> Creation of Individual Page

- src/components/pages/styles/IntelligentPagesStyles.ts
- src/hooks/insurance/useIntelligentPageQuery.tsx
- src/pages/intelligent-insurance-plans/index.tsx
This PR creates the ILG Page. 
Jira Ticket: [https://horizonmedia.atlassian.net/browse/NMB-137](https://horizonmedia.atlassian.net/browse/NMB-137)
> Creation of ILG Page

- src/components/pages/styles/IndividualPageStyle.ts
- src/components/pages/styles/IntelligentPagesStyles.ts
- src/hooks/insurance/useIndividualPageQuery.tsx
- src/hooks/insurance/useIntelligentPageQuery.tsx
- src/pages/health-insurance/individual/index.tsx
- src/pages/intelligent-insurance-plans/index.tsx
**Release Version:** v10.13.23
**Release Date:** 10/13/23
- [NMB-137](https://horizonmedia.atlassian.net/browse/NMB-137):  ILG Unique LP
- [NMB-83](https://horizonmedia.atlassian.net/browse/NMB-83):  Individual Page 
Before approving this pull request, reviewers should verify the following:
**Reviewers:**
> Release: 10/13/23

- src/components/pages/styles/IndividualPageStyle.ts
- src/pages/health-insurance/individual/index.tsx
This PR contains a temporary hotfix to remove BrightEdge from being used for the Individual Page.
> Hotfix: Temporary hotfix Brightedge

- src/components/Hero/PageHeroForm/index.tsx
This PR update the Connecture API to use 2024 plans instead of 2023.
Jira Ticket: https://horizonmedia.atlassian.net/browse/NMB-310
> HOTFIX: Update connecture link to 2024 (core)

- src/components/pages/styles/homePageStyles.ts
- src/pages/index.tsx
This PR updates the Homepage Hero Section to be in season. 
| Before        | After          | 
| ------------- |:-------------:| 
|![Screenshot 2023-10-23 at 9 41 59 AM](https://github.com/HorizonMedia/HealthMarketWebsite/assets/141367316/249ded42-5140-4cae-9bc9-1a155bc33fbc)|![Screenshot 2023-10-23 at 9 42 21 AM](https://github.com/HorizonMedia/HealthMarketWebsite/assets/141367316/5d6dc586-c65e-4b1d-b922-5bd030f9d1b1)|
Jira Ticket: https://horizonmedia.atlassian.net/browse/NMB-293
Figma: https://www.figma.com/file/9xftUKeRnWmIPr65vwYYGx/CLIENT-Countdown-Clock?type=design&node-id=505-834&mode=design&t=kvvgpWofDpH9lN3r-0
> NMB-293: In Season Hero Change
